package GameEngine;

public enum PlayState {
    BEGINNING_STATE,
    FILLING_EMPTY_COUNTRIES,
    USING_REMAINING_ARMIES,
    PLAYER_PLACING_ARMIES,
    PLAYER_CONVERTING_CARDS,
    PLAYER_INVADING_COUNTRY,
    PLAYER_MOVING_ARMIES,
    PLAYER_ENDED_GO,
}