package GameEngine;

public enum RequestReason {
	PLACING_ARMIES_SET_UP,
	PLACING_REMAINING_ARMIES_PHASE,
	PLACING_ARMIES_PHASE,
	ATTACK_CHOICE,
	DEFEND_CHOICE,
	REINFORCEMENT_PHASE,
	POST_ATTACK_MOVEMENT
}
