package GameEngine;

public enum RequestReason {
	PLACING_ARMIES_SET_UP,
	PLACING_REMAINING_ARMIES_PHASE,
	PLACING_ARMIES_PHASE,
	ATTACK_CHOICE_FROM,
	ATTACK_CHOICE_TO,
	ATTACK_CHOICE_DICE,
	DEFEND_CHOICE_DICE,
	REINFORCEMENT_PHASE,
	POST_ATTACK_MOVEMENT
}
